import { defineStore } from 'pinia';

export const useLangStore = defineStore('lang', {
  state: () => ({
    lang: localStorage.getItem('lang') || 'id'
  }),
  actions: {
    toggleLang() {
      this.lang = this.lang === 'id' ? 'en' : 'id';
      localStorage.setItem('lang', this.lang);
    },
    setLang(newLang) {
      this.lang = newLang;
      localStorage.setItem('lang', newLang);
    }
  },
  getters: {
    t: (state) => {
      const dictionary = {
        id: {
          dashboard: 'Dashboard',
          radar: 'Peta Radar',
          explore: 'Cari',
          report: 'Laporkan',
          chat: 'Chat',
          profile: 'Profil',
          admin: 'Admin Panel',
          logout: 'Keluar',
          welcome: 'Halo',
          subtitle: 'Selamat datang di Pawpaw Finder.',
          compare: 'Bandingkan',
          stories: 'Cerita',
          quiz: 'Kuis',
          activeReports: 'Laporan Aktif',
          successSaved: 'Berhasil Diselamatkan',
          successRate: 'Tingkat Keberhasilan',
          quickActions: 'Aksi Cepat',
          reportLost: 'Lapor Hewan Hilang',
          reportFound: 'Lapor Hewan Ditemukan',
          exploreCatalog: 'Eksplorasi Katalog',
          radarMap: 'Radar Peta',
          quickHelp: 'Bantuan Cepat',
          adoptTitle: 'Ingin Mengadopsi Teman Baru?',
          adoptSub: 'Kunjungi portal adopsi resmi kami untuk menemukan anabul impianmu.',
          adoptBtn: 'Buka Pawpaw Adopt',
          back: 'Kembali',
          send: 'Kirim',
          contact: 'Kontak',
          description: 'Deskripsi',
          status: 'Status',
          type: 'Jenis',
          color: 'Warna',
          location: 'Lokasi',
          date: 'Tanggal',
          name: 'Nama',
          detail: 'Detail',
          editProfile: 'Edit Profil',
          myReports: 'Laporan Saya',
          discussions: 'Diskusi',
          bookmarks: 'Bookmark',
          fullname: 'Nama Lengkap',
          bio: 'Bio',
          domicile: 'Domisili',
          phone: 'Nomor Kontak',
          save: 'Simpan',
          loading: 'Memproses...',
          uploading: 'Mengunggah...',
          photo: 'Foto',
          changePhoto: 'Ubah Foto Profil',
          address: 'Alamat',
          clickMap: 'Klik pada peta untuk menandai lokasi kejadian',
          selectedCoords: 'Koordinat terpilih',
          submitReport: 'Kirim Laporan',
          searchPet: 'Cari Hewan',
          petName: 'Nama Hewan',
          foundAt: 'Ditemukan di',
          lostAt: 'Hilang di',
          missing: 'Hilang',
          found: 'Ditemukan',
          contactReporter: 'Hubungi Pelapor',
          aiMatch: 'Jalankan Deteksi AI Kesesuaian',
          downloadWanted: 'Cetak Brosur WANTED (PDF)',
          qrEmergency: 'QR Code Darurat',
          scanQrInfo: 'Scan kode ini untuk info darurat & kontak',
          aiMatchResultTitle: 'Deteksi Selesai',
          aiMatchResultText: 'AI mendeteksi kecocokan sebesar',
          aiMatchResultWith: 'dengan laporan di wilayah',
          viewRelatedReports: 'Lihat Laporan Terkait',
          chats: 'Pesan Masuk',
          noadopt_chats: 'Belum ada percakapan.',
          roomChat: 'Ruang Obrolan',
          moveToWA: 'Pindah ke WhatsApp',
          typeMessage: 'Ketik pesan...',
          selectConversation: 'Pilih Percakapan',
          selectConversationDesc: 'Klik pada salah satu obrolan di samping untuk mulai membalas.',
          adminControl: 'Ruang Kendali Admin',
          verifyReports: 'Verifikasi Laporan',
          manageUsers: 'Manajemen User',
          exportSummary: 'Export Rekapitulasi',
          resetDb: 'Reset Database (Seed)',
          pendingReports: 'Laporan Tertunda',
          loadingReports: 'Memuat data laporan...',
          noPendingReports: 'Tidak ada laporan yang perlu diverifikasi saat ini.',
          loadingUsers: 'Memuat data pengguna...',
          approve: 'Approve',
          delete: 'Hapus',
          idReport: 'ID Laporan',
          idUser: 'ID User',
          role: 'Role',
          action: 'Aksi',
          adoption: 'Adopsi',
          adoptionCatalog: 'Katalog Adopsi',
          searchAdoption: 'Cari anabul yang siap diadopsi...',
          petAdoption: 'Adopsi Hewan',
          adoptMe: 'Ajukan Adopsi',
          healthStatus: 'Status Kesehatan',
          vaccinated: 'Vaksinasi',
          sterilized: 'Sterilisasi',
          weight: 'Berat Badan',
          breed: 'Ras',
          age: 'Umur',
          gender: 'Jenis Kelamin',
          healthHistory: 'Riwayat Kesehatan',
          petOwner: 'Shelter / Pemilik',
          aboutPet: 'Tentang Hewan',
          noPetsReady: 'Tidak ada hewan adopsi yang sesuai kriteria.',
          pending: 'Menunggu',
          approved: 'Disetujui',
          rejected: 'Ditolak',
          fullName: 'Nama Lengkap',
          phone: 'Nomor HP',
          address: 'Alamat Lengkap',
          experience: 'Pengalaman Memelihara',
          reason: 'Alasan Mengadopsi',
          submitRequest: 'Kirim Pengajuan',
          requestSuccess: 'Pengajuan adopsi berhasil dikirim!',
          petCareExperience: 'Ceritakan pengalaman Anda memelihara hewan...',
          reasonToAdopt: 'Mengapa Anda ingin mengadopsi hewan ini?',
          allSpecies: 'Semua Jenis',
          allLocations: 'Semua Lokasi',
          allAges: 'Semua Umur',
          allGenders: 'Semua Jenis Kelamin',
          young: 'Muda (< 1 tahun)',
          adult: 'Dewasa (1-5 tahun)',
          senior: 'Tua (> 5 tahun)',
          male: 'Jantan',
          female: 'Betina'
        },
        en: {
          dashboard: 'Dashboard',
          radar: 'Radar Map',
          explore: 'Search',
          report: 'Report',
          chat: 'Chat',
          profile: 'Profile',
          admin: 'Admin Panel',
          logout: 'Log Out',
          welcome: 'Hello',
          subtitle: 'Welcome to Pawpaw Finder.',
          compare: 'Compare',
          stories: 'Stories',
          quiz: 'Quiz',
          activeReports: 'Active Reports',
          successSaved: 'Successfully Saved',
          successRate: 'Success Rate',
          quickActions: 'Quick Actions',
          reportLost: 'Report Lost Pet',
          reportFound: 'Report Found Pet',
          exploreCatalog: 'Explore Catalog',
          radarMap: 'Radar Map',
          quickHelp: 'Quick Help',
          adoptTitle: 'Want to Adopt a New Friend?',
          adoptSub: 'Visit our official adoption portal to find your dream fur baby.',
          adoptBtn: 'Open Pawpaw Adopt',
          back: 'Back',
          send: 'Send',
          contact: 'Contact',
          description: 'Description',
          status: 'Status',
          type: 'Type',
          color: 'Color',
          location: 'Location',
          date: 'Date',
          name: 'Name',
          detail: 'Detail',
          editProfile: 'Edit Profile',
          myReports: 'My Reports',
          discussions: 'Discussions',
          bookmarks: 'Bookmarks',
          fullname: 'Full Name',
          bio: 'Bio',
          domicile: 'Domicile',
          phone: 'Contact Number',
          save: 'Save',
          loading: 'Processing...',
          uploading: 'Uploading...',
          photo: 'Photo',
          changePhoto: 'Change Profile Photo',
          address: 'Address',
          clickMap: 'Click on the map to pin the incident location',
          selectedCoords: 'Selected coordinates',
          submitReport: 'Submit Report',
          searchPet: 'Search Pet',
          petName: 'Pet Name',
          foundAt: 'Found at',
          lostAt: 'Lost at',
          missing: 'Missing',
          found: 'Found',
          contactReporter: 'Contact Reporter',
          aiMatch: 'Run AI Match Detection',
          downloadWanted: 'Print WANTED Flyer (PDF)',
          qrEmergency: 'Emergency QR Code',
          scanQrInfo: 'Scan this code for emergency info & contact',
          aiMatchResultTitle: 'Detection Complete',
          aiMatchResultText: 'AI detected a match of',
          aiMatchResultWith: 'with reports in the area of',
          viewRelatedReports: 'View Related Reports',
          chats: 'Inbox',
          noadopt_chats: 'No adopt_chats yet.',
          roomChat: 'Chat Room',
          moveToWA: 'Move to WhatsApp',
          typeMessage: 'Type a message...',
          selectConversation: 'Select Conversation',
          selectConversationDesc: 'Click on one of the adopt_chats on the side to start replying.',
          adminControl: 'Admin Control Center',
          verifyReports: 'Verify Reports',
          manageUsers: 'User Management',
          exportSummary: 'Export Recap',
          resetDb: 'Reset Database (Seed)',
          pendingReports: 'Pending Reports',
          loadingReports: 'Loading report data...',
          noPendingReports: 'No reports need verification at this time.',
          loadingUsers: 'Loading user data...',
          approve: 'Approve',
          delete: 'Delete',
          idReport: 'Report ID',
          idUser: 'User ID',
          role: 'Role',
          action: 'Action',
          adoption: 'Adoption',
          adoptionCatalog: 'Adoption Catalog',
          searchAdoption: 'Search pets ready for adoption...',
          petAdoption: 'Pet Adoption',
          adoptMe: 'Adopt Me',
          healthStatus: 'Health Status',
          vaccinated: 'Vaccinated',
          sterilized: 'Sterilized',
          weight: 'Weight',
          breed: 'Breed',
          age: 'Age',
          gender: 'Gender',
          healthHistory: 'Health History',
          petOwner: 'Shelter / Owner',
          aboutPet: 'About Pet',
          noPetsReady: 'No pets match the adoption criteria.',
          pending: 'Pending',
          approved: 'Approved',
          rejected: 'Rejected',
          fullName: 'Full Name',
          phone: 'Phone Number',
          address: 'Full Address',
          experience: 'Care Experience',
          reason: 'Reason to Adopt',
          submitRequest: 'Submit Application',
          requestSuccess: 'Adoption application submitted successfully!',
          petCareExperience: 'Describe your pet care experience...',
          reasonToAdopt: 'Why do you want to adopt this pet?',
          allSpecies: 'All Species',
          allLocations: 'All Locations',
          allAges: 'All Ages',
          allGenders: 'All Genders',
          young: 'Young (< 1 year)',
          adult: 'Adult (1-5 years)',
          senior: 'Senior (> 5 years)',
          male: 'Male',
          female: 'Female'
        }
      };

      return (key) => {
        return dictionary[state.lang][key] || key;
      };
    }
  }
});
